### ISSUE TITLE
How does this compare to YouCompleteMe?

### ISSUE THREAD

**Issue by tnguyen14** [ajh17/VimCompletesMe#28]
I am currently using YouCompleteMe, but this plugin piqued my interest. I like the idea that it is much simpler and more minimal. Could you provide some aspects that this plugin does not do? I just want to have a better understanding before switching over. Most likely I don't need those features anyway. I just wanted to be a bit more informed.

**Comment by ajh17** [comment]
Hi, thanks for checking VimCompletesMe out!

Basically, VCM modifies the Tab key (or any other key you choose) to be more context aware. If you're completing after a period, it might offer you omni completion. If you press the Tab key after a file path, it'll use Vim's file path completion, etc.

So, this plugin just uses Vim's internal auto completion (`:help ins-completion` in Vim will tell you all about the various completion Vim already has) and because of that, it's much more minimal than YouCompleteMe.

**Comment by tnguyen14** [comment]
Thank you for the response!

Other than being activated by the Tab key, is there other ways to invoke VCM?

Also, if I weren't using this plugin, how else could I invoke vim's internal auto completion?

**Comment by ajh17** [comment]
As I mentioned previously, you can choose another key instead of the Tab key. 

Vim internal completion system, as I also mentioned before is explained in `:help ins-completion` (type that in Vim). The help page will do a far better job at explaining things than I can.

**Comment by tnguyen14** [comment]
Ok. Thanks for your prompt response :)
