### ISSUE TITLE
relative directory completion

### ISSUE THREAD

**Issue by andrewdelprete** [ajh17/VimCompletesMe#44]
Hi there, I'm using JavaScript ES6 Modules and the `import` method to import modules, libraries, etc... It looks like VimCompletesMe file completion uses the current `pwd` so things like this won't autocomplete properly.

```
// projectName/js/components/MyComponent.js

import Modal from '../Modal'
```

When trying to autocomplete `../modal` and hitting tab, it starts the directory at `projectName`.

Any suggestions? Thanks!

**Comment by ajh17** [comment]
Hi,

Yep, this is expected. VimCompletesMe actually uses Vim’s built in File Completion (invoked via Vim’s built in key binding `Ctrl-X Ctrl-F`. VimCompletesMe just makes it easier so Tab will use `Ctrl-x ctrl-f`for you smartly depending on the situation so you don’t have to remember the key sequence or have to type it yourself.

Thus, this issue is not related to VimCompletesMe but to Vim’s completion behavior itself.

Now to solve this issue, you could just change the current working directory in Vim. `Ctrl-X Ctrl-F` in Vim uses the current working directory, so you can just change the current working directory by running: `:cd projectName/js/components/` in Vim.

See also `:help autocd`.

Since this issue is not related to VimCompletesMe, I’ll close this issue.
