### ISSUE TITLE
Error when python3 only

### ISSUE THREAD

**Issue by m3at** [ajh17/VimCompletesMe#46]
Hi,
With vim compiled with python3 but not python, give an `Error: Required vim compiled with +python` upon trying to complete in a python file.  
`Ctrl-n_Ctrl-n` works in the same file.

Vim version:
```
% vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
[...]
Features included (+) or not (-):
-python      +python3
[...]
```

Is there a way around this issue?

**Comment by ajh17** [comment]
This isn't really a VimCompletesMe issue. You're running into this problem because the default python3complete that is shipped with Vim assumes +python, and not +python3. But, python3complete is also shipped with vim. So maybe you could have a file similar to what I do to get around this issue. That is, to set the omnicompletion for python manually to python3complete:

https://github.com/ajh17/dotfiles/blob/master/.vim/after/ftplugin/python.vim#L6

**Comment by m3at** [comment]
Make sense.
Steps to solve if someone encounter a similar issue:

Option 1) edit the file that currently set `omnifunc`:
You can get the last file that set it with `:verb set omnifunc?`, in my case
`vim +20 /usr/share/vim/vim74/ftplugin/python.vim`
Edit to `setlocal omnifunc=python3complete#Complete`

Option 2) overwrite:
Create or edit `/path/to/your/vim/conf/.vim/after/ftplugin/python.vim` as @ajh17 suggested:
```
" Tab completion
let b:vcm_tab_complete = "omni"

" Use python3 completion if we're linked against python3. For some reason,
" this isn't done by default
let b:python_exe = has("python3") ? "python3" : "python"
if b:python_exe ==# "python3"
  setlocal omnifunc=python3complete#Complete
  setlocal makeprg=python3\ %
else
  " Omnifunc is correctly set here by built-in pythoncomplete.vim
  setlocal makeprg=python\ %
endif
```

I'll close this issue, thanks :)
