### ISSUE TITLE
Don't flip vcm_direction when popping up the menu

### ISSUE THREAD

**Issue by fictionic** [ajh17/VimCompletesMe#50]
For some reason, the user's direction preference is swapped when the tab key is first pressed. If direction is `p`, then hitting tab invokes `<C-N>`, and if it's `n` then tab invokes `<C-P>`. This is flatly in the code (look for 'HERE'):

In `function! s:vim_completes_me`:
```
  if is_omni_pattern && (!empty(&omnifunc))
    " Check position so that we can fallback if at the same pos.
    if get(b:, 'tab_complete_pos', []) == pos && b:completion_tried
      let exp = "\<C-x>" . dirs[!dir]  <-- HERE
    else
      echo "Looking for members..."
      let exp = (!empty(&completefunc) && map ==? "user") ? "\<C-x>\<C-u>" : "\<C-x>\<C-o>"
      let b:completion_tried = 1
    endif
    let b:tab_complete_pos = pos
    return exp
  elseif is_file_pattern
    return "\<C-x>\<C-f>"
  endif

  " First fallback to keyword completion if special completion was already tried.
  if exists('b:completion_tried') && b:completion_tried
    let b:completion_tried = 0
    return "\<C-e>" . dirs[!dir]  <-- HERE
  endif

  " Fallback
  let b:completion_tried = 1
  if map ==? "user"
    return "\<C-x>\<C-u>"
  elseif map ==? "omni"
    echo "Looking for members..."
    return "\<C-x>\<C-o>"
  elseif map ==? "vim"
    return "\<C-x>\<C-v>"
  else
    return dirs[!dir]   <-- AND HERE
  endif
```

The proper behavior (in my opinion) is achieved by simply removing the three `!`s.

Clearly this was a choice; what I don't know is why. As it currently is, pressing tab a second time will always make the menu selection go to the null selection, which is pretty darn inconvenient. It's such an easy fix I don't think it's worth submitting a pull request, but I can if you want. Mostly I just want to know what the story is.

Thanks for such a great lightweight plugin!

**Comment by ajh17** [comment]
Firstly, the variable "vcm_direction" is only for the popup menu. Setting it to "p" just reverses the direction of the selection so that Tab == Shift-Tab in the popup menu, and thus the selection starts from the bottom of the list and goes up rather than the top of the list going down.

Secondly, getting a null selection when hitting Tab seems to be a bug, can you provide an example for this?

What I think might be happening is that, VimCompletesMe performs a context switch depending on whether or not there is a "special" (omni/user/vim) completion match. If there wasn't, a second tab would revert to the normal "Ctrl-N/Ctrl-P" completion.

**Comment by fictionic** [comment]
> Firstly, the variable "vcm_direction" is only for the popup menu. Setting it to "p" just reverses the direction of the selection so that Tab == Shift-Tab in the popup menu, and thus the selection starts from the bottom of the list and goes up rather than the top of the list going down.

I don't think that's actually what's going on, though, looking at the function `s:vim_completes_me`. The boolean `dir` is defined to be whether or not `g:vcm_direction` matches `[nf]`. If the popup menu is open, the direction of traversal is `g:vcm_direction` for `<Tab>` and the opposite of `g:vcm_direction` for `<S-Tab>`, as you claim. But `dir` is used several times after that. Importantly, in the middle block, you have `return "\<C-e>" . dirs[!dir]`. This means that when the user first presses tab to pop up the completion menu, and only keyword completion can be used, it will be invoked through `<C-P>` if `g:vcm_direction == 'n'` and through `<C-N>` if `g:vcm_direction == 'p'`—the opposite of what they intend. At least when I use the plugin, I want `<Tab>` to invoke keyword completion in a consistent direction.

The issue is a little weird because keyword completion can be invoked in two ways, whereas all the other methods only have one way. All I'm suggesting is that the way it's invoked is consistent with `vcm_direction`, since otherwise you have to wrap around the completion menu first.

> Secondly, getting a null selection when hitting Tab seems to be a bug, can you provide an example for this?

No it's not a bug, it's builtin vim behavior. Open a file where you can do some completion and run `<C-P><C-N>`. It'll say "back at original" at the bottom. With this plugin's current behavior, this is what happens every time keyword completion is used.

> What I think might be happening is that, VimCompletesMe performs a context switch depending on whether or not there is a "special" (omni/user/vim) completion match. If there wasn't, a second tab would revert to the normal "Ctrl-N/Ctrl-P" completion, after restarting it with `:help complete_Ctrl-E`

That is also relevant, since you've negated `dir` in the code for that case as well. And thanks for the tip about `complete__Ctrl-E`! I was wondering why that was in there haha

**Comment by fictionic** [comment]
(wrong button)

**Comment by ajh17** [comment]
You know what, honestly thinking about this, I think you're right. I know I had a good reason for reversing the dir variable, but as much as I rack my brains about it, I can't think of that reason, and it was so long ago when the plugin was still being constructed. I believe it probably had to do with using Ctrl-P by default, which to me feels "right". For instance, when looking for completion suggestions, what the user wants to complete would be before the current cursor location, and not after.

I know other users have also brought this issue up, and I've been hesitant to change it since I've always preferred it this way, but I'm willing to let this one go since I do see what you're saying and it is the most intuitive option, and we can go ahead and keep the vcm_direction consistent as well.

Do you mind creating the pull request for this? I'll go ahead and merge it then. Thanks so much!

**Comment by fictionic** [comment]
Done!
