### ISSUE TITLE
Changes due to #51 fix

### ISSUE THREAD

**Issue by pauloue** [ajh17/VimCompletesMe#52]
1. Maybe the default `g:vcm_direction` should be changed to 'p' since it's more likely that what you are trying to complete is before the current position? Before #51 the default was 'n', but it started searching backwards with the first tab press and then searched forward with subsequent tabs.

2. The docs could be updated (faq question 2 and the vcm_direction option).

**Comment by ajh17** [comment]
That's true, currently it's selecting the first item if `set completeopt-=longest`. I will fix this. 

I will also introduce a new variable to control the direction within the popup menu when it's open because currently it's not too intuitive since it's opposite to the vcm_direction setting. I'll update the docs for this as well.

Thanks for letting me know!

**Comment by pauloue** [comment]
I'm not sure what you mean in the second paragraph. How is it opposite the direction setting? Currently with vcm_direction set to 'n', pressing tab twice is equivalent to pressing ctrl+n twice (find the next match twice) and with it set to 'p' 2 tabs finds the previous match twice. If the direction within the menu was different than the initial tab press it would first find the next/previous match then go back to the original (no completion). My completeopt is the default.

**Comment by ajh17** [comment]
I meant that the direction within the popup menu is reversed. Most people expect Tab to advance to the next occurrence.

For example, with the default settings and vcm_direction == 'p', in the below text file (where | is the cursor):

```
foob
foo
f|
food
```

The popup menu opens with "foo" selected first, as expected, and pressing Tab would traverse back up the list instead of forwards, which is not what most people would expect, even though I actually prefer it go back up the list rather than forwards since what I want to complete is most likely before my cursor.

If I reverse the Tab behavior, "foo" is selected first (even though it's the most bottom entry), then pressing Tab again would jump back out of the list, and restart from the top of the list.

**Comment by pauloue** [comment]
It will restart from the top of the list, but isn't this really the end of the list? When I try this with two buffers open, when it jumps to the top it's showing me completions from the other file. In your example it first selects "foo", then jumps to the top (the end of the completion list) and finds "food". This would not be expected behavior because if you have vcm_direction == 'p', you would want to match words before your cursor first.

Also I think having it start at the bottom, then go to no completion, then jump to the top would be less intuitive that starting from the bottom of the menu and moving up.

**Comment by ajh17** [comment]
Oh I agree with you, but I'm debating which one to have as a default.

1. "p" is default. In this case it would start from the bottom of the list and move up the list when you press Tab.
2. "n" is default. In this case, it would start from the top of the list and move down the list when you press Tab.

I find that people generally like it when Tab selects the next entry rather than the previous one, even though option 1 is more "correct", since as we said– the word you're completing is most likely before the cursor position.

So I'm leaning towards keeping "n" as the default.

**Comment by pauloue** [comment]
That works. I just didn't see the point in having another option to control the direction within the menu.

**Comment by fictionic** [comment]
Hey guys. Person who committed https://github.com/ajh17/VimCompletesMe/pull/51 here. I just realized there was an underlying problem with the implementation. The variable `vcm_direction` is meant to let the user choose whether they want Tab to act as `<C-P>` or as `<C-N>`—this makes sense. But it only makes sense when talking about keyword completion. Keyword completion is based solely on the order that words appear in the buffer (or other buffers). A user might reasonably want to choose whether to be given the words that appear right above the cursor or right below the cursor, in general. But all the other types of completion aren't like this: they are coded to give you options in a single order that is best, and the order is presented from top-down. So there is no reason one would want to traverse this list backwards by default. Moreover, the other completions cannot be initiated backwards like keyword completion can, so you always start at the top.

Here is my proposal.  
For keyword completion, `<Tab>` should, depending on a user setting, act like one of `<C-P>` or `<C-N>` throughout, both for the initial keypress and for traversing the menu; `<S-Tab>` should do the opposite. For the other types of completion that VCM can invoke automatically, the behavior of `<Tab>` should depend on whether or not the menu is open. When it's not open, `<Tab>` should invoke the command to enter the proper completion mode (e.g. `<C-X><C-O>`), and `<S-Tab>` should do the same but start the user at the bottom of the menu (e.g. `<C-X><C-O><C-P><C-P>` to loop around the top). When the menu is already open, `<Tab>` should invoke `<C-N>`, and `<S-Tab>` should invoke `<C-P>`—there should be no setting to reverse this (or if there is, it should be a separate setting from the keyword completion one).

What do you think?

**Comment by fictionic** [comment]
Ok here's the first problem with this: if the user gets into the omnicompletion menu manually, VCM wouldn't know about it, and so pressing `<Tab>` would do the wrong thing, because it wouldn't have been able to set the variable that remembers that it's in omnicompletion mode and not keyword completion mode. A solution would be to wrap `<C-X><C-O>` (and the other non-keyword completions) with functions that set the variable.

**Comment by ajh17** [comment]
@fictionic: Yep, I think that's an apt summary. I actually like the way that "p" direction works. Like I said, even though it's "backwards", words /are/ selected in the order that they appear before the cursor position.

But I also agree that this is not always appropriate.

VCM tries to be agnostic as possible about the current file, and how Vim presents the list, and only tries to do the "right thing" when the popup menu is shown. The vcm_direction was purely meant as the direction that the Tab would navigate within the popup menu, but I admit that this got confused with "selecting words that are located before the cursor position first".

**Comment by ajh17** [comment]
> Ok here's the first problem with this: if the user gets into the (e.g.) omnicompletion menu manually, VCM wouldn't know about it, and so pressing <Tab> would do the wrong thing, because it wouldn't have been able to set the variable that remembers that it's in a non-keyword-completion mode. A solution would be to wrap <C-X><C-O> (and the other non-keyword completion commands) with functions that set the right variable.

I'm okay with this. Re-mapping all C-X_* keymappings is not what I want to do with VCM.

**Comment by ajh17** [comment]
I'm reverting #51 for now, if someone wants to take another shot at it, feel free.

**Comment by fictionic** [comment]
Ok I tried my hand and ended up basically overhauling the whole thing. I couldn't figure out why the code was structured the way it was, with different if-else blocks just laying about, so I just wrote it the way I imagined it would need to work. The only problem I'm aware of is that if you hit tab and enter omnicomplete mode, and there are no results, hitting tab will put you back in keyword completion mode, then back to omnicomplete mode. Not sure why, and it's not really a big deal, but it bugs me.

[Have a look.](https://github.com/fictionic/VimCompletesMe/blob/master/plugin/VimCompletesMe.vim)

**Comment by fictionic** [comment]
@ajh17 Have you had time to look at my fork? I'm really curious what you think.

**Comment by ajh17** [comment]
@fictionic: I did but I only skimmed it. I'll take a look more at it fully once I get a good amount of free time.

Can you create a pull request so I can see the diffs easier and comment on some of the confusing parts that I don't understand from your fork?

**Comment by ajh17** [comment]
I'll close this issue and you can create a pull request instead.
