### ISSUE TITLE
Persistent omnicompletion split with function info

### ISSUE THREAD

**Issue by SiliconKite** [ajh17/VimCompletesMe#56]
It works great out of the box but I am having one little issue. When the autocompletion works for omnicompletion (python language), a split opens on top with the info of the function being completed. However I can't get rid of this split afterwards. Any idea? Thanks

I am on vim 8.0

**Comment by ajh17** [comment]
This feature is not added by VimCompletesMe, but it's a built in vim feature called preview window. You can read about it in `:help preview-window`

Vim's default `completeopt` (See `:help completeopt`) setting includes showing the preview window, which omnicompletion plugins can use.

You can either remove the preview window from completeopt (`set completeopt-=preview)` or, do what I do, since I like the preview information: [close it when you exit InsertMode](https://github.com/ajh17/dotfiles/blob/49596a7e15d1b024a83176f3cc6ca0a7d527c205/.vimrc#L144)

Hope this helps!

**Comment by ajh17** [comment]
Closing this since this is unrelated to VCM, but feel free to comment if you need more help.

**Comment by SiliconKite** [comment]
thanks so much for the quick reply. the automatic closing works like a charm
