### ISSUE TITLE
Completion starts at the bottom of the list and then cycles forward

### ISSUE THREAD

**Issue by scwood** [ajh17/VimCompletesMe#7]
I'm not sure if this is intended or not, but when I hit tab, the selection starts at the last menu option, and then cycles forward. What this means is the second time hitting tab results in no completion, and the third goes back to the top of the list and starts down. 

If I reverse the completion direction, the first item in the list is selected, and then it goes backwards, meaning again that the second time hitting tab results in the menu being off the completion. 

The only other plugins I'm using are syntastic, vim-surround, and vim-tmux-navigator.

The desired for me would be starting at the top, and going down the completion list, or starting at the bottom and going up the completion list. Is this an issue on my end?

**Comment by ajh17** [comment]
Yes, this seems to be a problem on your end. When I hit tab, the first menu item is selected and then the completion cycles forward. You can see what I get when I hit Tab here: https://asciinema.org/a/16214 

What is your completeopt setting? You can find out by executing  `set completeopt?`

**Comment by scwood** [comment]
My set completeopt? returns completeopt=menu.

**Comment by ajh17** [comment]
That seems fine. Are you able to replicate my completion shown in the video using VimCompleteMe's default settings? 

Is it highlighting the last menu item when you press Tab, and then it cycles forward to the first menu item?

**Comment by scwood** [comment]
No I am not unfortunately. I'm getting some weird behavior... https://asciinema.org/a/16216

Cycling is messed up, and on shorter patterns, tab is just inserting an N to the end of my word and not finding existing patterns. I'm sort of confused, I don't have any setopt settings or completion settings or anything in my [vimrc](https://github.com/scwood/dotfiles/blob/master/vimrc).

And yes that is correct. With default settings, the last menu item is highlighted first and then it cycles forward.

**Comment by ajh17** [comment]
Yep, I'm able to reproduce this issue. I found what the bug is. Currently fixing it now.

Thanks!

**Comment by scwood** [comment]
Thanks for your help!

**Comment by ajh17** [comment]
Just to clarify, only the first issue is a bug, i.e. when you hit tab and you get 'n' inserted.

The second issue is not a bug. This is by design. Hitting tab will search backwards, not forwards from the cursor position. Most of the time, you want to complete words that are already defined in the buffer before the cursor position.

Since 'syntax' was before your cursor, that is what is selected when you hit Tab.

**Comment by scwood** [comment]
What about the completion menu starting at the bottom and traveling down/starting at the top and traveling up? Shouldn't it be behaving like it is in your video?

**Comment by ajh17** [comment]
First, my behavoior was because I have 'let b:vcm_tab_complete = "vim"' in my ftplugin/vim.vim file. This means that VimCompletesMe will use Vim's command line completion first before trying keyword completion if there are no matches.

Second, I have set 'completeopt=menu,longest,menuone'. So it will complete to the longest common matching string and then show me the popup menu *after*. When the popup menu is opened, VimCompletesMe will automatically cycle forward (by default). This is why it starts from the first completion entry. 

Since you didn't have longest, the popup menu is opened *before* showing the popup menu. This means that the word is selected before the popup menu is shown. I hope this makes sense.

**Comment by scwood** [comment]
So I added `completeopt=menu,longest,menuone` I get this behavior: https://asciinema.org/a/16217

It now doesn't start at the bottom, but it also isn't automatically cycling forward by one. Am I missing something else?

**Comment by ajh17** [comment]
The n appearing issue should now be fixed.

However, feel free to reopen this if you disagree with something or need more help, I'll be happy to assist in any way I can!

**Comment by ajh17** [comment]
Regarding your completeopt setting, yep, this is what Vim's default completion acts like. It will first complete to the longest string, and then open the popup menu without selecting anything.

**Comment by scwood** [comment]
Okay, thanks for your help. Learned some new things today!

**Comment by ajh17** [comment]
Reopening this because it looks like I didn't totally fix the first issue.

**Comment by lowmanb94** [comment]
I know that this issue has been closed, but I cannot seem to understand why  the `dir` variable is negated when querying the `dirs` list in lines 55, 66, and 82. Changing these lines to `dirs[dir]` produces the default behavior for `<c-n>` and `<c-p`> completions corresponding to `g:vcm_direction = 'n'` and `g:vcm_direction = 'p'`, respectively.  

I don't know a lick of vimscript however, and there may very well be a reason it is coded up this way.

**Comment by ajh17** [comment]
@lowmanb94 Good question.

It's just a matter of personal preference. 

When completing, I find that the keyword I'm trying to complete is more likely to be found before the cursor position (`:help Ctrl-x_Ctrl-p`), rather than after (`:help Ctrl-x_Ctrl-n`). You can of course reverse this behavior if you want by setting the `g:vcm_direction`.

**Comment by lowmanb94** [comment]
@ajh17 
I agree with you, but I still don't understand why you would call both `dirs[dir]` and `dirs[!dir]` (that is, `<c-n> and <c-p>`) given any one setting of `g:vcm_direction`. 

If `g:vcm_direction='n'`, when I tab for the first time, the status text at the bottom is telling me `<c-p>` is executed. Any subsequent tab presses result in `<c-n>` completions. Given `g:vmc_direction = 'p'`, the opposite occurs.

**Comment by ajh17** [comment]
Can you show me a screenshot of this? 

With completion of keywords, it should start with `Ctrl-P` by default (`dirs[!dir]`) and when the popup is open, it will use `Ctrl-n` (`dirs[dir]`) to advance forward to the next item in the popup menu.

**Comment by lowmanb94** [comment]
Ahh okay so we are on the same page about the current behavior, then. That is indeed exactly what happens. I would just expect that *all* tab presses execute the same kind of completion. If you do this manually, repeated presses of `<c-n>` march down the list starting from the first element, and repeated presses of `<c-p>` march up the list starting with the last element.

**Comment by ajh17** [comment]
Yep, VimCompletesMe just maps `<Tab>` to `Ctrl-n` and `<S-Tab>` (shift-tab) to `Ctrl-p` when the popup menu is open

**Comment by lowmanb94** [comment]
Just to be super duper sure -- [this](https://vid.me/tGfw) is behavior you intend?  With all defaults (including `completeopt=menu,preview`), this is what happens for me when I repeatedly press tab.

Thanks for your patience

**Comment by ajh17** [comment]
Yep, that is exactly the default behavior. shiftwidth is highlighted because that's the previous word before the cursor, Ctrl-N, then, just cycles forward the list. This is similar to typing Ctrl-p and then Ctrl-n to cycle forward the list.

I like to have `set completeopt+=longest` so it completes to the longest matching string and then pops up the completion, so you always start at the head of the list. :)

**Comment by lowmanb94** [comment]
Thanks!
 
I might suggest that you add a little blurb in the docs about this. The README led me to believe that repeated presses of tab would just keep querying `<c-n>` completion (and conversely, setting `g:vcm_direction` to 'p') would repeatedly query `<c-p>` completion.

**Comment by ajh17** [comment]
Yeah, I completely agree with you. Since this has now become a FAQ, I'll add it in there. :smile:

Thank you!
